### ISSUE TITLE
App loading time too long

### ISSUE THREAD

**Issue by cgunes** [vbresults/mobile-apps#71]
### 1.2. Which platform(s) does your issue occur on?
Both

### 1.3. Version numbers that your issue occurs with:
- iOS App: (e.g. 1.2.0)
- Android App: (e.g. 1.2.0)
- Platform (choose): XenForo
- Add-on Version: (e.g. 1.2.0)
- XenForo Version: (e.g. 1.5.5)

## 3. Do you have a question?
The app takes too long to load. Sometimes 30-40 seconds. Is it possible to make it load faster in future versions

**Comment by vbresults** [comment]
We deliberately choose to not hide the splash screen until the 1st page is fully loaded (this way you don't see the page loading), but this is inconsistent with how browsers work.

This is problematic because if you are on a fast connection, the splash screen is gone quickly.  But if you are on a slow connection, this can take a proportionately higher amount of time;

This is echoed by someone's post here: https://theadminzone.com/threads/a-new-mobile-app.139923/page-3#post-1049897

The expected behavior is to have the splash screen only show for a fixed amount of time (1 second) and the show the page loading so we'll implement this in 1.2.4 (1.2.3 is already published).
