### ISSUE TITLE
cant login using twitter/fb

### ISSUE THREAD

**Issue by king8084** [vbresults/mobile-apps#74]
## 1. Are you reporting an issue with the apps or add-ons?
Yes
### 1.1. If so, tell us about the problem
-- Details --
cant login using twitter/fb
### 1.2. Which platform(s) does your issue occur on?
Both

### 1.3. Version numbers that your issue occurs with:
- iOS App: (e.g. 1.1.40)
- Android App: (e.g. 1.1.40)
- Platform (choose): XenForo, vBulletin, WordPress
- Add-on Version: (e.g. 1.1.40)
- XenForo Version: (e.g. 1.5.5)

### 1.4. Please tell us how to recreate the issue in detail
-- Details --

### 1.5. Is there an error message involved?  If so, please paste
-- Details --

## 2. Are you requesting a new feature?
Yes/No

### 2.1. If so, delete everything above #2, describe your idea
-- Details --

## 3. Do you have a question?
Yes/No

### 3.1. If so, enter your question
-- Details --

**Comment by vbresults** [comment]
This was discovered yesterday and a fix has already been implemented, it will be deployed tomorrow; by the way, until the last issue regarding Google is resolved you still have email support;

I'll follow up by email on that issue when there's an update

**Comment by vbresults** [comment]
As mentioned in our earlier email ticket, in regards to the "login" issue members have reported which we've been talking about, it's not actually a login issue;

It's the app sending people outside of the app (safari/chrome) to log in, and they do successfully log in -- but they are logged into safari/chrome, *not the app* the login happened in the wrong place.

This issue is fixed in .32 as tagged above; it should be available on Android in a few hours if it isn't already, and on iOS in 4 to 5 days (:
