### ISSUE TITLE
clicking links does nothing in app

### ISSUE THREAD

**Issue by king8084** [vbresults/mobile-apps#80]
## 1. Are you reporting an issue with the apps or add-ons?
Yes/
### Are you running the latest version of the app(s) and add-on?
Yes

### Did you verify this is a real problem by searching the [other tickets](https://github.com/vbresults/mobile-apps/issues?q=is%3Aissue+is%3Aclosed)?
Yes
### 1.1. If so, tell us about the problem
-- Details --
this issue is also found with TAZ so it is not just an issue for me

### 1.2. Which platform(s) does your issue occur on?
iOS/Android/Both

### 1.3. Version numbers that your issue occurs with:
- iOS App: (e.g. 1.1.40)
- Android App: (e.g. 1.1.40)
- Platform (choose): XenForo, vBulletin, WordPress
- Add-on Version: (e.g. 1.1.40)
- XenForo Version: (e.g. 1.5.5)

### 1.4. Please tell us how to recreate the issue in detail
-- Details --

### 1.5. Is there an error message involved?  If so, please paste
-- Details --

## 2. Are you requesting a new feature?
Yes/No

### 2.1. If so, delete everything above #2, describe your idea
-- Details --

## 3. Do you have a question?
Yes/No

### 3.1. If so, enter your question
-- Details --

**Comment by vbresults** [comment]
Was only here to release the latest update, and I'm stepping out now as it's Friday night, but before I left I thought to let you know that I found what might be causing this problem and if you follow the cache reset instructions in the latest update email, this issue should be resolved;

Also, in the future, fill out as much details as possible in the ticket template otherwise it will take longer to resolve the issue because we have almost no information to track the problem down.

Good night (:

**Comment by vbresults** [comment]
I accidentally ran into this issue and it turns out that this happens when the net connection is lost (which is why I had trouble reproducing the problem);

I'll follow up with the fix details on Tuesday (:

**Comment by vbresults** [comment]
An offline notice is coming in 1.2.41 (:

**Comment by king8084** [comment]
this is not fixed, confirmed still an issue

please check

**Comment by vbresults** [comment]
@king8084 What device and OS, and is it happening only for external links or internal links too?

**Comment by vbresults** [comment]
This issue and the one you reported a day ago are actually two separate issues -- it has been split into a separate ticket and fixed as an instant fix #86
