### ISSUE TITLE
my app still wont show worldwide in ios

### ISSUE THREAD

**Issue by king8084** [vbresults/mobile-apps#81]
## 1. Are you reporting an issue with the apps or add-ons?
Yes
### Are you running the latest version of the app(s) and add-on?
Yes

### Did you verify this is a real problem by searching the [other tickets](https://github.com/vbresults/mobile-apps/issues?q=is%3Aissue+is%3Aclosed)?
No

### 1.1. If so, tell us about the problem
-- Details --
my app doesnt show in africa/middle east stores 
### 1.2. Which platform(s) does your issue occur on?
iOS

### 1.3. Version numbers that your issue occurs with:
- iOS App: (e.g. 1.1.40)
- Android App: (e.g. 1.1.40)
- Platform (choose): XenForo, vBulletin, WordPress
- Add-on Version: (e.g. 1.1.40)
- XenForo Version: (e.g. 1.5.5)

### 1.4. Please tell us how to recreate the issue in detail
-- Details --

### 1.5. Is there an error message involved?  If so, please paste
-- Details --

## 2. Are you requesting a new feature?
Yes/No

### 2.1. If so, delete everything above #2, describe your idea
-- Details --

## 3. Do you have a question?
Yes/No

### 3.1. If so, enter your question
-- Details --

**Comment by vbresults** [comment]
Hello,

Here are some screenshots from the developer console:

![screen shot 2016-05-05 at 10 41 03 am](https://cloud.githubusercontent.com/assets/7179668/15034179/f8a8e6d4-12ad-11e6-97d5-1178a08a37cc.png)
![screen shot 2016-05-05 at 10 41 24 am](https://cloud.githubusercontent.com/assets/7179668/15034184/fe79aa08-12ad-11e6-8be6-fac3e00dfba4.png)

If you don't see it on certain stores, it is because it is blocked from the country not by us, but by their content rating requirements, because we have selected all of the stores.

Does all of this make sense?

**Comment by vbresults** [comment]
No response to the ticket; closing
